name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Cambia "main" si tu rama principal tiene otro nombre
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Descargar el código fuente del repositorio
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      # Instalar dependencias, compilar y construir el sitio Astro
      - name: Install dependencies, build, and upload your site
        uses: withastro/action@v3
        env:
          PUBLIC_GS_API_URL: 'https://script.google.com/macros/s/AKfycbxYlFrkler72r3bCIxLF2xryxGvwCF8EZrriPrEa_gvYoJhvYe5yXcUwTgUn_nffKoVhw/exec'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Desplegar el sitio a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4